# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7af84af819fef4609bef09e58a20a5c7e2fc6a0f8ae0a439653d0e8cc619c8ccb53de9ff17219ea7253b02a1b0ba74f0c20539612ab0d11241a28ef083639cc6

test:
  secret_key_base: 359f15158f4ab4e456a1438a1eef37aa14e201d39e9f08fdfb5e09b756673b0413f156156ef29642336fc666e41d86db2293df6cd36a5696bdd3425510fb1b89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
